### ISSUE TITLE
Example is broken

### ISSUE THREAD

**Issue by aaronzshey** [aaronzshey/react-hexgrid#30]
For some reason the basic example says this when run:

Starting the development server...

/Users/aaron/react-hexgrid/examples/basic-board/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

TypeError: fsevents.watch is not a function
    at createFSEventsInstance (/Users/aaron/react-hexgrid/examples/basic-board/node_modules/chokidar/lib/fsevents-handler.js:94:25)
    at setFSEventsListener (/Users/aaron/react-hexgrid/examples/basic-board/node_modules/chokidar/lib/fsevents-handler.js:150:16)
    at FsEventsHandler._watchWithFsEvents (/Users/aaron/react-hexgrid/examples/basic-board/node_modules/chokidar/lib/fsevents-handler.js:353:18)
    at FsEventsHandler.initWatch (/Users/aaron/react-hexgrid/examples/basic-board/node_modules/chokidar/lib/fsevents-handler.js:429:23)
    at FsEventsHandler._addToFsEvents (/Users/aaron/react-hexgrid/examples/basic-board/node_modules/chokidar/lib/fsevents-handler.js:518:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.4.0

**Comment by aaronzshey** [comment]
Examples have been replaced by Storybook tutorials.
